# Generated by Django 4.2.6 on 2024-02-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodations',
            name='ammenities',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accomodations',
            name='description',
            field=models.TextField(),
        ),
    ]
