# Generated by Django 5.0.2 on 2024-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_alter_accomodationtype_accomodationpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefiles',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
