# Generated by Django 4.2.6 on 2023-12-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accomodations', '0002_accomodations_imagefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodations',
            name='acc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accomodations.accomodationtype'),
            preserve_default=False,
        ),
    ]
