# Generated by Django 5.0.2 on 2024-03-18 21:17

import apps.locations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=200, unique=True)),
                ('locationPic', models.ImageField(upload_to=apps.locations.models.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
