# Generated by Django 4.2.6 on 2023-11-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='name',
            new_name='locationName',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='picture',
            new_name='locationPic',
        ),
    ]
