# Generated by Django 5.0.2 on 2024-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourPackages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='packagePic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
