# Generated by Django 5.0.2 on 2024-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
