# Generated by Django 4.2.6 on 2024-01-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0002_alter_sites_dest_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sites',
            name='dest_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
