# Generated by Django 4.2.6 on 2024-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sites', '0003_alter_sites_description_alter_sites_dest_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='activities',
            field=models.TextField(),
        ),
    ]
