# Generated by Django 4.2.6 on 2023-11-27 12:07

import apps.destinations.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_rename_name_locations_locationname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=200, unique=True)),
                ('activities', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('destinationPic', models.ImageField(upload_to=apps.destinations.models.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locations')),
            ],
        ),
    ]
