# Generated by Django 5.0.2 on 2024-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
