# Generated by Django 4.2.6 on 2023-11-09 13:50

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=models.ImageField(upload_to=apps.users.models.path_and_rename),
        ),
    ]
